name: Validate dotnet

on: [ pull_request, push ]

jobs:
  setup-version:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    name: dotnet test
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            6.0.x
            7.0.x
            8.0.x
      - run: dotnet test RecordParser.Test/RecordParser.Test.csproj
